---
# The kubernetes version impacts the prometheus scraping endpoint
# so gathering it before constructing the configmap
- name: get oc version
  oc_version:
  register: oc_version

- set_fact:
    kubernetes_version: "{{ oc_version.results.kubernetes_short | float }}"
    openshift_prometheus_service_annotations: "{{ l_openshift_prometheus_service_annotations + openshift_prometheus_service_annotations|list }}"
    openshift_prometheus_alerts_service_annotations: "{{ l_openshift_prometheus_alerts_service_annotations + openshift_prometheus_alerts_service_annotations|list }}"
    openshift_prometheus_alertmanager_service_annotations: "{{ l_openshift_prometheus_alertmanager_service_annotations + openshift_prometheus_alertmanager_service_annotations|list }} "
    openshift_prometheus_serviceaccount_annotations: "{{ l_openshift_prometheus_serviceaccount_annotations + openshift_prometheus_serviceaccount_annotations|list }}"
