---
- name: Install iSCSI storage plugin dependencies
  package: name=iscsi-initiator-utils state=present
  when: not openshift_is_atomic | bool
  register: result
  until: result is succeeded
  with_items:
    - iscsi-initiator-utils
    - device-mapper-multipath

- name: restart udev
  systemd:
    name: systemd-udevd
    state: restarted
    daemon_reload: yes
  with_items:
    - multipathd
    - rpcbind

- name: Tempalte multipath configuration
  template:
    dest: "/etc/multipath.conf"
    src: multipath.conf.j2
    backup: true
  when: not openshift_is_atomic | bool

#enable multipath
- name: Enable multipath
  command: "mpathconf --enable"
  when: not openshift_is_atomic | bool
  notify:
    - restart multipathd
