---
# This task list checks for unsupported configurations. Values here should yield
# a partially functioning cluster but would not be supported for production use.

- name: Ensure that openshift_use_dnsmasq is true
  when:
  - not openshift_use_dnsmasq | default(true) | bool
  fail:
    msg: |-
      Starting in 3.6 openshift_use_dnsmasq must be true or critical features
      will not function. This also means that NetworkManager must be installed
      enabled and responsible for management of the primary interface.

- name: Ensure the hosted registry's GlusterFS storage is configured correctly
  when:
  - openshift_hosted_registry_storage_kind | default(none) in ['glusterfs']
  - openshift_hosted_registry_storage_glusterfs_ips is defined and openshift_hosted_registry_storage_glusterfs_ips != ''
  - "'glusterfs_registry' in groups | default([])"
  fail:
    msg: |-
      Configuring a value for openshift_hosted_registry_storage_glusterfs_ips and with a glusterfs_registry host group is not allowed.
      Specifying a glusterfs_registry host group indicates that a new GlusterFS cluster should be configures, whereas
      specifying openshift_hosted_registry_storage_glusterfs_ips indicates wanting to use a pre-configured GlusterFS cluster for the registry storage.

- name: Ensure registry's backend is configured correctly
  when:
  - openshift_hosted_registry_storage_kind | default(none) in ['glusterfs']
  - not openshift_hosted_registry_storage_glusterfs_ips is defined
  - "not 'glusterfs_registry' in groups | default([])"
  - "not 'glusterfs' in groups | default([])"
  fail:
    msg: |-
      Configuring a value for openshift_hosted_registry_storage_kind=glusterfs without variable openshift_hosted_registry_storage_glusterfs_ips or glusterfs, glusterfs_registry groups is not allowed.
      Specifying a  openshift_hosted_registry_storage_kind=glusterfs indicates that a GlusterFS backend will be used for registry without specifying which GlusterFS to use.
